version: '3.7'

services:
  app:
    build: '.'
    restart: unless-stopped
    tty: true
    volumes:
      - './:/srv/app:rw'
    networks:
      - backend
    environment:
      - PHP_IDE_CONFIG=serverName=instagram-scraper

  nginxapi:
    image: 'nginx:1.17.0-alpine'
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    volumes:
      - './docker/nginx/conf.d/:/etc/nginx/conf.d/:ro'
      - './:/srv/app:rw'
    ports:
      - '8084:80'
    networks:
      - backend

volumes:
  dbdata:
    driver: local

networks:
  backend:
    driver: bridge